/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoresIndexRouteImport } from './routes/produtores.index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as CasasIndexRouteImport } from './routes/casas.index'
import { Route as BandasIndexRouteImport } from './routes/bandas.index'
import { Route as ProdutoresIdRouteImport } from './routes/produtores.$id'
import { Route as EventosIdRouteImport } from './routes/eventos.$id'
import { Route as CasasCadastrarRouteImport } from './routes/casas.cadastrar'
import { Route as CasasIdRouteImport } from './routes/casas.$id'
import { Route as BandasIdRouteImport } from './routes/bandas.$id'
import { Route as ApoiarBandaIdRouteImport } from './routes/apoiar.$bandaId'
import { Route as AuthenticatedMinhaBandaRouteImport } from './routes/_authenticated/minha-banda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoresIndexRoute = ProdutoresIndexRouteImport.update({
  id: '/produtores/',
  path: '/produtores/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasasIndexRoute = CasasIndexRouteImport.update({
  id: '/casas/',
  path: '/casas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BandasIndexRoute = BandasIndexRouteImport.update({
  id: '/bandas/',
  path: '/bandas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoresIdRoute = ProdutoresIdRouteImport.update({
  id: '/produtores/$id',
  path: '/produtores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIdRoute = EventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasasCadastrarRoute = CasasCadastrarRouteImport.update({
  id: '/casas/cadastrar',
  path: '/casas/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CasasIdRoute = CasasIdRouteImport.update({
  id: '/casas/$id',
  path: '/casas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BandasIdRoute = BandasIdRouteImport.update({
  id: '/bandas/$id',
  path: '/bandas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoiarBandaIdRoute = ApoiarBandaIdRouteImport.update({
  id: '/apoiar/$bandaId',
  path: '/apoiar/$bandaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMinhaBandaRoute = AuthenticatedMinhaBandaRouteImport.update({
  id: '/minha-banda',
  path: '/minha-banda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/minha-banda': typeof AuthenticatedMinhaBandaRoute
  '/apoiar/$bandaId': typeof ApoiarBandaIdRoute
  '/bandas/$id': typeof BandasIdRoute
  '/casas/$id': typeof CasasIdRoute
  '/casas/cadastrar': typeof CasasCadastrarRoute
  '/eventos/$id': typeof EventosIdRoute
  '/produtores/$id': typeof ProdutoresIdRoute
  '/bandas/': typeof BandasIndexRoute
  '/casas/': typeof CasasIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/produtores/': typeof ProdutoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/minha-banda': typeof AuthenticatedMinhaBandaRoute
  '/apoiar/$bandaId': typeof ApoiarBandaIdRoute
  '/bandas/$id': typeof BandasIdRoute
  '/casas/$id': typeof CasasIdRoute
  '/casas/cadastrar': typeof CasasCadastrarRoute
  '/eventos/$id': typeof EventosIdRoute
  '/produtores/$id': typeof ProdutoresIdRoute
  '/bandas': typeof BandasIndexRoute
  '/casas': typeof CasasIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/produtores': typeof ProdutoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/minha-banda': typeof AuthenticatedMinhaBandaRoute
  '/apoiar/$bandaId': typeof ApoiarBandaIdRoute
  '/bandas/$id': typeof BandasIdRoute
  '/casas/$id': typeof CasasIdRoute
  '/casas/cadastrar': typeof CasasCadastrarRoute
  '/eventos/$id': typeof EventosIdRoute
  '/produtores/$id': typeof ProdutoresIdRoute
  '/bandas/': typeof BandasIndexRoute
  '/casas/': typeof CasasIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/produtores/': typeof ProdutoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/ranking'
    | '/termos'
    | '/admin'
    | '/minha-banda'
    | '/apoiar/$bandaId'
    | '/bandas/$id'
    | '/casas/$id'
    | '/casas/cadastrar'
    | '/eventos/$id'
    | '/produtores/$id'
    | '/bandas/'
    | '/casas/'
    | '/eventos/'
    | '/produtores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/ranking'
    | '/termos'
    | '/admin'
    | '/minha-banda'
    | '/apoiar/$bandaId'
    | '/bandas/$id'
    | '/casas/$id'
    | '/casas/cadastrar'
    | '/eventos/$id'
    | '/produtores/$id'
    | '/bandas'
    | '/casas'
    | '/eventos'
    | '/produtores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/ranking'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/minha-banda'
    | '/apoiar/$bandaId'
    | '/bandas/$id'
    | '/casas/$id'
    | '/casas/cadastrar'
    | '/eventos/$id'
    | '/produtores/$id'
    | '/bandas/'
    | '/casas/'
    | '/eventos/'
    | '/produtores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RankingRoute: typeof RankingRoute
  TermosRoute: typeof TermosRoute
  ApoiarBandaIdRoute: typeof ApoiarBandaIdRoute
  BandasIdRoute: typeof BandasIdRoute
  CasasIdRoute: typeof CasasIdRoute
  CasasCadastrarRoute: typeof CasasCadastrarRoute
  EventosIdRoute: typeof EventosIdRoute
  ProdutoresIdRoute: typeof ProdutoresIdRoute
  BandasIndexRoute: typeof BandasIndexRoute
  CasasIndexRoute: typeof CasasIndexRoute
  EventosIndexRoute: typeof EventosIndexRoute
  ProdutoresIndexRoute: typeof ProdutoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtores/': {
      id: '/produtores/'
      path: '/produtores'
      fullPath: '/produtores/'
      preLoaderRoute: typeof ProdutoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casas/': {
      id: '/casas/'
      path: '/casas'
      fullPath: '/casas/'
      preLoaderRoute: typeof CasasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandas/': {
      id: '/bandas/'
      path: '/bandas'
      fullPath: '/bandas/'
      preLoaderRoute: typeof BandasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtores/$id': {
      id: '/produtores/$id'
      path: '/produtores/$id'
      fullPath: '/produtores/$id'
      preLoaderRoute: typeof ProdutoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$id': {
      id: '/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof EventosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casas/cadastrar': {
      id: '/casas/cadastrar'
      path: '/casas/cadastrar'
      fullPath: '/casas/cadastrar'
      preLoaderRoute: typeof CasasCadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casas/$id': {
      id: '/casas/$id'
      path: '/casas/$id'
      fullPath: '/casas/$id'
      preLoaderRoute: typeof CasasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandas/$id': {
      id: '/bandas/$id'
      path: '/bandas/$id'
      fullPath: '/bandas/$id'
      preLoaderRoute: typeof BandasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoiar/$bandaId': {
      id: '/apoiar/$bandaId'
      path: '/apoiar/$bandaId'
      fullPath: '/apoiar/$bandaId'
      preLoaderRoute: typeof ApoiarBandaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/minha-banda': {
      id: '/_authenticated/minha-banda'
      path: '/minha-banda'
      fullPath: '/minha-banda'
      preLoaderRoute: typeof AuthenticatedMinhaBandaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMinhaBandaRoute: typeof AuthenticatedMinhaBandaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMinhaBandaRoute: AuthenticatedMinhaBandaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RankingRoute: RankingRoute,
  TermosRoute: TermosRoute,
  ApoiarBandaIdRoute: ApoiarBandaIdRoute,
  BandasIdRoute: BandasIdRoute,
  CasasIdRoute: CasasIdRoute,
  CasasCadastrarRoute: CasasCadastrarRoute,
  EventosIdRoute: EventosIdRoute,
  ProdutoresIdRoute: ProdutoresIdRoute,
  BandasIndexRoute: BandasIndexRoute,
  CasasIndexRoute: CasasIndexRoute,
  EventosIndexRoute: EventosIndexRoute,
  ProdutoresIndexRoute: ProdutoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
